packages:
  - "apps/mobile/*"
  - "apps/template/*"
  - "apps/web/*"
  - "apps/desktop/*"
  - "labs/*"
  - "packages/*"
  - "packages/ai/*"
  - "packages/config/*"
  - "packages/infra/*"
  - "packages/domain/*"
  - "packages/entity/*"
  - "packages/ui/*"
  - "packages/feature/*"
  - "packages/resource/*"
